/* Main application logic */

// Application initialization
(function() {
  'use strict';

  // State and persistence management
  window.appState = {
    user: null,
    role: null,
    isAdmin: false
  };

  // Load state from localStorage
  function loadState() {
    try {
      const roleContext = localStorage.getItem('roleContext');
      const authContext = localStorage.getItem('authContext');
      
      if (roleContext) {
        const role = JSON.parse(roleContext);
        window.appState.role = role;
      }
      
      if (authContext) {
        const auth = JSON.parse(authContext);
        window.appState.user = auth;
      }
      
      updateAdminStatus();
    } catch (e) {
      console.error('Error loading state:', e);
    }
  }

  // Save state to localStorage
  function saveState() {
    try {
      if (window.appState.role) {
        localStorage.setItem('roleContext', JSON.stringify(window.appState.role));
      }
      if (window.appState.user) {
        localStorage.setItem('authContext', JSON.stringify(window.appState.user));
      }
    } catch (e) {
      console.error('Error saving state:', e);
    }
  }

  // Admin gating logic
  function updateAdminStatus() {
    const isAdmin = 
      window.appState.role === 'Admin' ||
      (window.appState.user && window.appState.user.role === 'Admin') ||
      (window.appState.user && isEmailInAdminList(window.appState.user.email));
    
    window.appState.isAdmin = isAdmin;
    updateAdminVisibility();
  }

  function isEmailInAdminList(email) {
    // TODO: Load admin list from settings/configuration
    const adminList = ['admin@example.com'];
    return email && adminList.includes(email.toLowerCase());
  }

  function updateAdminVisibility() {
    const adminElements = document.querySelectorAll('[data-admin-only]');
    adminElements.forEach(el => {
      if (window.appState.isAdmin) {
        el.removeAttribute('hidden');
      } else {
        el.setAttribute('hidden', '');
      }
    });
  }

  // Reset session
  window.resetSession = function() {
    localStorage.removeItem('roleContext');
    localStorage.removeItem('authContext');
    window.appState = { user: null, role: null, isAdmin: false };
    updateAdminVisibility();
    location.reload();
  };

  // Set role (for testing/role selector)
  window.setRole = function(role) {
    window.appState.role = role;
    saveState();
    updateAdminStatus();
  };

  // Preview mode (Desktop/Mobile toggle)
  window.setPreviewMode = function(mode) {
    const root = document.querySelector('[data-testid="TID-SHELL-ROOT"]');
    if (!root) return;
    
    if (mode === 'mobile') {
      root.classList.add('mobile-preview');
      root.setAttribute('data-preview-mode', 'mobile');
      // Update button states
      document.querySelector('[data-testid="TID-PREVIEW-MOBILE"]')?.classList.add('active');
      document.querySelector('[data-testid="TID-PREVIEW-DESKTOP"]')?.classList.remove('active');
    } else {
      root.classList.remove('mobile-preview');
      root.setAttribute('data-preview-mode', 'desktop');
      // Update button states
      document.querySelector('[data-testid="TID-PREVIEW-DESKTOP"]')?.classList.add('active');
      document.querySelector('[data-testid="TID-PREVIEW-MOBILE"]')?.classList.remove('active');
    }
    
    console.log('Preview mode set to:', mode);
  };

  // Health Check Runner (calls backend QA system)
  window.runHealthCheck = async function() {
    const reportDisplay = document.getElementById('health-report-display');
    const strictMode = document.getElementById('strict-mode-toggle')?.checked || false;
    
    if (!reportDisplay) return;
    
    // Show loading state
    reportDisplay.innerHTML = `
      <div style="text-align: center; padding: 40px;">
        <div style="font-size: 2rem; margin-bottom: 16px;">⏳</div>
        <p style="font-size: 1.25rem; color: #64748b;">Running health checks...</p>
        <p style="font-size: 0.875rem; color: #94a3b8;">This may take a moment</p>
      </div>
    `;
    
    try {
      // Load ACTUAL QA results from last-result.json (generated by run-qa.ps1)
      const response = await fetch('qa/last-result.json');
      
      if (response.ok) {
        const report = await response.json();
        displayHealthReport(report);
      } else {
        // Fallback: show instructions to run QA
        reportDisplay.innerHTML = `
          <div class="filter-card" style="background: #fef3c7; border-left: 4px solid #f59e0b;">
            <h3 style="color: #92400e; margin-top: 0;">QA Report Not Available</h3>
            <p style="color: #78350f;">To run the full QA check suite, execute this command:</p>
            <pre style="background: #1e293b; color: #e2e8f0; padding: 12px; border-radius: 4px; overflow-x: auto;">./scripts/run-qa.ps1</pre>
            <p style="color: #78350f; margin-bottom: 0;">The report will appear here once generated.</p>
          </div>
        `;
      }
    } catch (error) {
      console.error('Health check error:', error);
      reportDisplay.innerHTML = `
        <div class="filter-card" style="background: #fee; border-left: 4px solid #ef4444;">
          <h3 style="color: #991b1b; margin-top: 0;">Error Running Health Check</h3>
          <p style="color: #7f1d1d;">${error.message}</p>
          <p style="color: #7f1d1d; margin-bottom: 0;">Please ensure the QA system is properly configured and accessible.</p>
        </div>
      `;
    }
  };

  // Display health report in UI
  function displayHealthReport(report) {
    const reportDisplay = document.getElementById('health-report-display');
    if (!reportDisplay) return;
    
    const summary = report.summary || { total: 0, passed: 0, failed: 0, skipped: 0 };
    const overallStatus = report.overallStatus || 'UNKNOWN';
    
    // Status color mapping
    let statusColor, statusBg, statusIcon;
    if (overallStatus === 'GREEN') {
      statusColor = '#10b981';
      statusBg = '#d1fae5';
      statusIcon = '✓';
    } else if (overallStatus === 'AMBER') {
      statusColor = '#f59e0b';
      statusBg = '#fef3c7';
      statusIcon = '⚠';
    } else {
      statusColor = '#ef4444';
      statusBg = '#fee';
      statusIcon = '✗';
    }
    
    let html = `
      <div class="filter-card" style="background: ${statusBg}; border-left: 4px solid ${statusColor};">
        <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 16px;">
          <h3 style="color: ${statusColor === '#10b981' ? '#065f46' : statusColor === '#f59e0b' ? '#92400e' : '#991b1b'}; margin: 0;">
            ${statusIcon} QA Status: ${overallStatus}
          </h3>
          <span style="color: #64748b; font-size: 0.875rem;">${new Date(report.timestamp).toLocaleString()}</span>
        </div>
        <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 16px;">
          <div>
            <div style="font-size: 0.75rem; color: #64748b; text-transform: uppercase;">Total Checks</div>
            <div style="font-size: 1.5rem; font-weight: bold; color: #1e293b;">${summary.total}</div>
          </div>
          <div>
            <div style="font-size: 0.75rem; color: #64748b; text-transform: uppercase;">Passed</div>
            <div style="font-size: 1.5rem; font-weight: bold; color: #10b981;">${summary.passed}</div>
          </div>
          <div>
            <div style="font-size: 0.75rem; color: #64748b; text-transform: uppercase;">Failed</div>
            <div style="font-size: 1.5rem; font-weight: bold; color: #ef4444;">${summary.failed}</div>
          </div>
          <div>
            <div style="font-size: 0.75rem; color: #64748b; text-transform: uppercase;">Skipped</div>
            <div style="font-size: 1.5rem; font-weight: bold; color: #94a3b8;">${summary.skipped}</div>
          </div>
        </div>
        <p style="margin: 0; color: ${statusColor === '#10b981' ? '#065f46' : statusColor === '#f59e0b' ? '#92400e' : '#991b1b'};">
          ${overallStatus === 'GREEN' ? '✓ All systems operational. Architecture compliance verified.' : 
            overallStatus === 'AMBER' ? '⚠ All critical checks passed, but some high-severity checks failed.' :
            '✗ Critical checks failed. Immediate remediation required.'}
        </p>
      </div>
    `;
    
    // Display checks grouped by category
    if (report.checks && report.checks.length > 0) {
      // Group checks by category
      const byCategory = {};
      report.checks.forEach(check => {
        const cat = check.category || 'other';
        if (!byCategory[cat]) byCategory[cat] = [];
        byCategory[cat].push(check);
      });
      
      html += '<div style="margin-top: 16px;">';
      
      for (const [category, checks] of Object.entries(byCategory)) {
        const categoryFailed = checks.filter(c => c.status === 'FAIL').length;
        const categoryPassed = checks.filter(c => c.status === 'PASS').length;
        const categorySkipped = checks.filter(c => c.status === 'SKIP').length;
        
        html += `
          <details class="filter-card" style="margin-bottom: 12px;" ${categoryFailed > 0 ? 'open' : ''}>
            <summary style="cursor: pointer; font-weight: bold; padding: 8px; background: #f1f5f9; border-radius: 4px;">
              ${category.toUpperCase()} (✓ ${categoryPassed} | ✗ ${categoryFailed} | ⊝ ${categorySkipped})
            </summary>
            <div style="padding: 12px 8px;">
        `;
        
        checks.forEach(check => {
          let checkIcon, checkColor, checkBg;
          if (check.status === 'PASS') {
            checkIcon = '✓';
            checkColor = '#10b981';
            checkBg = '#f0fdf4';
          } else if (check.status === 'SKIP') {
            checkIcon = '⊝';
            checkColor = '#94a3b8';
            checkBg = '#f8fafc';
          } else {
            checkIcon = '✗';
            checkColor = '#ef4444';
            checkBg = '#fef2f2';
          }
          
          html += `
            <div style="margin-bottom: 8px; padding: 8px; background: ${checkBg}; border-radius: 4px;">
              <div style="display: flex; align-items: start; gap: 8px;">
                <span style="color: ${checkColor}; font-weight: bold;">${checkIcon}</span>
                <div style="flex: 1;">
                  <div style="font-weight: 500; color: #1e293b;">${check.id}: ${check.name}</div>
                  ${check.message ? `<div style="font-size: 0.875rem; color: #64748b; margin-top: 4px;">${check.message}</div>` : ''}
                  ${check.details ? `<div style="font-size: 0.75rem; color: #94a3b8; margin-top: 4px;">${check.details}</div>` : ''}
                  <div style="font-size: 0.75rem; color: #94a3b8; margin-top: 4px;">Severity: ${(check.severity || 'medium').toUpperCase()}</div>
                </div>
              </div>
            </div>
          `;
        });
        
        html += `
            </div>
          </details>
        `;
      }
      
      html += '</div>';
    }
    
    reportDisplay.innerHTML = html;
  }

  // Placeholder functions referenced in HTML
  window.saveProject = function() {
    console.log('saveProject called');
    if (typeof window.closeProjectSetup === 'function') {
      window.closeProjectSetup();
    }
  };

  window.runWiringChecks = function() {
    console.log('Running wiring checks...');
    // Placeholder for wiring checks
    return true;
  };

  window.computeStatusDescriptor = function(startDate, endDate, today = new Date()) {
    // Placeholder status computation
    if (!startDate || !endDate) return 'unknown';
    const start = new Date(startDate);
    const end = new Date(endDate);
    if (today < start) return 'not-started';
    if (today > end) return 'overdue';
    return 'in-progress';
  };

  // Initialize on DOMContentLoaded
  document.addEventListener('DOMContentLoaded', function() {
    loadState();
    
    // Set up hashchange listener for navigation
    window.addEventListener('hashchange', function() {
      const route = location.hash || '#/';
      if (typeof window.navigateTo === 'function') {
        window.navigateTo(route);
      }
    });
    
    // Initial navigation is handled by inline script after navigateTo is defined
  });

  console.log('app-main.js loaded');
})();
